version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          
workflows:
  send-notification:
    jobs:
      - notify:
          context: SLACK_DEFAULT_CHANNEL
